### PR TITLE
Add facilities to synthesize by other vendors

### PR DESCRIPTION
**Pull request by pdobacz**

### CODE REVIEW

**Comment by pdobacz** [comment]
Hold off review, my git client misled me, I need to resolve some conflicts

**Comment by pdobacz** [comment]
Ok, now better, good to review

**Review by yoid2000 — APPROVED** [review]
Was the style cleanup some automatic thing? There may be a lot of conflicts when you merge...

**Comment by pdobacz** [comment]
> Was the style cleanup some automatic thing? There may be a lot of conflicts when you merge...

No, I triggered it manually, do you want me to stop doing it?

**Comment by yoid2000** [comment]
I don't mind so long as it doesn't create merge issues

**Comment by pdobacz** [comment]
> I don't mind so long as it doesn't create merge issues

This time it doesn't so I'll leave it in, but I guess it will eventually, so maybe I'll be more selective in formatting in the next PRs

**Pull request merged**
